### ISSUE TITLE
the library can't parse message type 5 ("ShipStaticData")

### ISSUE THREAD

**Issue by Y-askour** [BertoldVdb/go-ais#17]
"!AIVDM,2,1,5,A,55?MbV02;H;s<HtKR20EHE:0@T4@Dn2222222216L961O5Gf0NSQEp6ClRp8,0*18" //5

**Comment by BertoldVdb** [comment]
Hello,

Your message 5 is not complete. Please supply both parts and it will decode on receipt of the last part.

**Comment by Y-askour** [comment]
how so can i get some help or some examples of messae 5 
i m a beginner in AIS

**Comment by Y-askour** [comment]
thanks a lot but how i can give a a two parts message to this library

**Comment by BertoldVdb** [comment]
Simply call ParseSentence twice, once with the first part and then with the second part.
